# network architecture
# encoder related
etype: lstm
elayers: 8
eunits: 2048
# decoder related
dlayers: 2
dunits: 2048
# attention related
adim: 256
aheads: 4

# hybrid CTC/attention
mtlalpha: 0.3

# label smoothing
lsm-weight: 0.1

# minibatch related
batch-size: 8
maxlen-in: 512  # if input length  > maxlen-in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen-out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: noam
accum-grad: 2
grad-clip: 5
patience: 0
epochs: 50
dropout-rate: 0.1
criterion: "loss"
early-stop-criterion: "validation/main/loss"


backend: pytorch
model-module: "espnet.nets.pytorch_backend.e2e_asr:E2E"

